/*
 * MainGUI.java
 *
 * Created on 12 de Janeiro de 2008, 19:37
 */

package br.gfca.openstereogram.gui;

import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author  Gustavo
 */
public class MainGUI extends javax.swing.JFrame {
    
    /** Creates new form MainGUI */
    public MainGUI() {
	initComponents();
	this.setLocationRelativeTo( null );
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Código Gerado ">//GEN-BEGIN:initComponents
    private void initComponents() {
        lookButtonGroup = new javax.swing.ButtonGroup();
        elementButtonGroup = new javax.swing.ButtonGroup();
        colorChooser = new javax.swing.JColorChooser();
        mapFileChooser = new javax.swing.JFileChooser();
        patternFileChooser = new javax.swing.JFileChooser();
        typePanel = new javax.swing.JPanel();
        lookLabel = new javax.swing.JLabel();
        dottedRadioButton = new javax.swing.JRadioButton();
        texturedRadioButton = new javax.swing.JRadioButton();
        elementLabel = new javax.swing.JLabel();
        textRadioButton = new javax.swing.JRadioButton();
        mapRadioButton = new javax.swing.JRadioButton();
        mapPatternPanel = new javax.swing.JPanel();
        textLabel = new javax.swing.JLabel();
        textTextField = new javax.swing.JTextField();
        sizeLabel = new javax.swing.JLabel();
        sizeSpinner = new javax.swing.JSpinner();
        mapLabel = new javax.swing.JLabel();
        mapPreviewPanel = new br.gfca.openstereogram.gui.ImagePreviewPanel();
        patternLabel = new javax.swing.JLabel();
        patternPreviewPanel = new br.gfca.openstereogram.gui.ImagePreviewPanel();
        parametersPanel = new javax.swing.JPanel();
        observationLabel = new javax.swing.JLabel();
        observationTextField = new javax.swing.JTextField();
        eyeLabel = new javax.swing.JLabel();
        eyeTextField = new javax.swing.JTextField();
        maxDepthLabel = new javax.swing.JLabel();
        maxDepthTextField = new javax.swing.JTextField();
        minDepthLabel = new javax.swing.JLabel();
        minDepthTextField = new javax.swing.JTextField();
        widthLabel = new javax.swing.JLabel();
        widthTextField = new javax.swing.JTextField();
        heighLabel = new javax.swing.JLabel();
        heighTextField = new javax.swing.JTextField();
        vPpiLabel = new javax.swing.JLabel();
        vPpiTextField = new javax.swing.JTextField();
        hPpiLabel = new javax.swing.JLabel();
        hPpiTextField = new javax.swing.JTextField();
        guidePanel = new javax.swing.JPanel();
        guideImagePanel = new javax.swing.JPanel();
        generateButton = new javax.swing.JButton();
        colorsPanel = new javax.swing.JPanel();
        color1Label = new javax.swing.JLabel();
        color1Panel = new javax.swing.JPanel();
        color2Label = new javax.swing.JLabel();
        color2Panel = new javax.swing.JPanel();
        color3Label = new javax.swing.JLabel();
        color3Panel = new javax.swing.JPanel();
        thirdColorCheckBox = new javax.swing.JCheckBox();
        intensityLabel = new javax.swing.JLabel();
        intensitySlider = new javax.swing.JSlider();
        percentLabel = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        helpMenu = new javax.swing.JMenu();
        helpMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        mapFileChooser.setCurrentDirectory(new File("./images/depthMaps/"));
        mapFileChooser.setDialogTitle("Open depth map");
        mapFileChooser.setFileFilter(new FileNameExtensionFilter("Image file (png, jpg, jpeg, gif, bmp)", "png", "jpg", "jpeg", "gif", "bmp"));
        patternFileChooser.setCurrentDirectory(new File("./images/texturePatterns/"));
        patternFileChooser.setDialogTitle("Open texture pattern");
        patternFileChooser.setFileFilter(new FileNameExtensionFilter("Image file (png, jpg, jpeg, gif, bmp)", "png", "jpg", "jpeg", "gif", "bmp"));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Open Stereogram");
        typePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lookLabel.setText("RDS look:");

        lookButtonGroup.add(dottedRadioButton);
        dottedRadioButton.setText("Dotted");
        dottedRadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        dottedRadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        dottedRadioButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                dottedRadioButtonStateChanged(evt);
            }
        });

        lookButtonGroup.add(texturedRadioButton);
        texturedRadioButton.setSelected(true);
        texturedRadioButton.setText("Textured");
        texturedRadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        texturedRadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));

        elementLabel.setText("Hidden element:");

        elementButtonGroup.add(textRadioButton);
        textRadioButton.setText("Text");
        textRadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        textRadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        textRadioButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                textRadioButtonStateChanged(evt);
            }
        });

        elementButtonGroup.add(mapRadioButton);
        mapRadioButton.setSelected(true);
        mapRadioButton.setText("Depth map");
        mapRadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        mapRadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));

        javax.swing.GroupLayout typePanelLayout = new javax.swing.GroupLayout(typePanel);
        typePanel.setLayout(typePanelLayout);
        typePanelLayout.setHorizontalGroup(
            typePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(typePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(typePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textRadioButton)
                    .addComponent(mapRadioButton)
                    .addComponent(dottedRadioButton)
                    .addComponent(texturedRadioButton)
                    .addComponent(lookLabel)
                    .addComponent(elementLabel))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        typePanelLayout.setVerticalGroup(
            typePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, typePanelLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lookLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dottedRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(texturedRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(elementLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mapRadioButton)
                .addGap(28, 28, 28))
        );

        mapPatternPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        textLabel.setText("Hidden text:");
        textLabel.setEnabled(false);

        textTextField.setText(" ");
        textTextField.setEnabled(false);

        sizeLabel.setText("Text size:");
        sizeLabel.setEnabled(false);

        sizeSpinner.setEnabled(false);
        sizeSpinner.setValue(180);

        mapLabel.setText("Depth map:");

        mapPreviewPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mapPreviewPanelMousePressed(evt);
            }
        });

        patternLabel.setText("Texture pattern:");

        patternPreviewPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                patternPreviewPanelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout mapPatternPanelLayout = new javax.swing.GroupLayout(mapPatternPanel);
        mapPatternPanel.setLayout(mapPatternPanelLayout);
        mapPatternPanelLayout.setHorizontalGroup(
            mapPatternPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mapPatternPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mapPatternPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textLabel)
                    .addComponent(textTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mapPatternPanelLayout.createSequentialGroup()
                        .addGroup(mapPatternPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mapLabel)
                            .addComponent(mapPreviewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(mapPatternPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(patternPreviewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(patternLabel))))
                .addGap(23, 23, 23)
                .addGroup(mapPatternPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sizeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sizeLabel))
                .addContainerGap())
        );
        mapPatternPanelLayout.setVerticalGroup(
            mapPatternPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mapPatternPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mapPatternPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textLabel)
                    .addComponent(sizeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mapPatternPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sizeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(mapPatternPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mapLabel)
                    .addComponent(patternLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mapPatternPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(patternPreviewPanel, 0, 0, Short.MAX_VALUE)
                    .addComponent(mapPreviewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        parametersPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        observationLabel.setText("Obs. distance:");

        observationTextField.setText("14");

        eyeLabel.setText("Eye separation:");

        eyeTextField.setText("2.5");

        maxDepthLabel.setText("Max. depth:");

        maxDepthTextField.setText("12");

        minDepthLabel.setText("Min. depth:");

        minDepthTextField.setText("0");

        widthLabel.setText("Width:");

        widthTextField.setText("640");

        heighLabel.setText("Heigh:");

        heighTextField.setText("480");

        vPpiLabel.setText("Vert. PPI:");

        vPpiTextField.setText("72");

        hPpiLabel.setText("Horiz. PPI:");

        hPpiTextField.setText("72");

        javax.swing.GroupLayout parametersPanelLayout = new javax.swing.GroupLayout(parametersPanel);
        parametersPanel.setLayout(parametersPanelLayout);
        parametersPanelLayout.setHorizontalGroup(
            parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parametersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(parametersPanelLayout.createSequentialGroup()
                        .addGroup(parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(widthLabel)
                                .addComponent(vPpiLabel)
                                .addComponent(observationTextField)
                                .addComponent(maxDepthTextField)
                                .addComponent(widthTextField)
                                .addComponent(vPpiTextField))
                            .addComponent(observationLabel))
                        .addGap(45, 45, 45)
                        .addGroup(parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(hPpiLabel)
                                .addComponent(minDepthLabel)
                                .addComponent(heighLabel)
                                .addComponent(eyeTextField)
                                .addComponent(minDepthTextField)
                                .addComponent(heighTextField)
                                .addComponent(hPpiTextField))
                            .addComponent(eyeLabel)))
                    .addComponent(maxDepthLabel))
                .addGap(60, 60, 60))
        );
        parametersPanelLayout.setVerticalGroup(
            parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parametersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eyeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(observationLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(observationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eyeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxDepthLabel)
                    .addComponent(minDepthLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxDepthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minDepthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(widthLabel)
                    .addComponent(heighLabel))
                .addGap(6, 6, 6)
                .addGroup(parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(widthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(heighTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vPpiLabel)
                    .addComponent(hPpiLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vPpiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hPpiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        guidePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        guideImagePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        javax.swing.GroupLayout guideImagePanelLayout = new javax.swing.GroupLayout(guideImagePanel);
        guideImagePanel.setLayout(guideImagePanelLayout);
        guideImagePanelLayout.setHorizontalGroup(
            guideImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 182, Short.MAX_VALUE)
        );
        guideImagePanelLayout.setVerticalGroup(
            guideImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 167, Short.MAX_VALUE)
        );

        generateButton.setText("Generate");
        generateButton.setEnabled(false);

        javax.swing.GroupLayout guidePanelLayout = new javax.swing.GroupLayout(guidePanel);
        guidePanel.setLayout(guidePanelLayout);
        guidePanelLayout.setHorizontalGroup(
            guidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(generateButton, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
            .addComponent(guideImagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        guidePanelLayout.setVerticalGroup(
            guidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, guidePanelLayout.createSequentialGroup()
                .addComponent(guideImagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(generateButton))
        );

        colorsPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        color1Label.setText("Color 1:");
        color1Label.setEnabled(false);

        color1Panel.setBackground(new java.awt.Color(255, 0, 0));
        color1Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        color1Panel.setEnabled(false);
        color1Panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                color1PanelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout color1PanelLayout = new javax.swing.GroupLayout(color1Panel);
        color1Panel.setLayout(color1PanelLayout);
        color1PanelLayout.setHorizontalGroup(
            color1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );
        color1PanelLayout.setVerticalGroup(
            color1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 71, Short.MAX_VALUE)
        );

        color2Label.setText("Color 2:");
        color2Label.setEnabled(false);

        color2Panel.setBackground(java.awt.Color.green);
        color2Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        color2Panel.setEnabled(false);
        color2Panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                color2PanelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout color2PanelLayout = new javax.swing.GroupLayout(color2Panel);
        color2Panel.setLayout(color2PanelLayout);
        color2PanelLayout.setHorizontalGroup(
            color2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        color2PanelLayout.setVerticalGroup(
            color2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 71, Short.MAX_VALUE)
        );

        color3Label.setText("Color 3:");
        color3Label.setEnabled(false);

        color3Panel.setBackground(java.awt.Color.blue);
        color3Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        color3Panel.setEnabled(false);
        color3Panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                color3PanelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout color3PanelLayout = new javax.swing.GroupLayout(color3Panel);
        color3Panel.setLayout(color3PanelLayout);
        color3PanelLayout.setHorizontalGroup(
            color3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        color3PanelLayout.setVerticalGroup(
            color3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 71, Short.MAX_VALUE)
        );

        thirdColorCheckBox.setSelected(true);
        thirdColorCheckBox.setText("3rd color");
        thirdColorCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        thirdColorCheckBox.setEnabled(false);
        thirdColorCheckBox.setMargin(new java.awt.Insets(0, 0, 0, 0));
        thirdColorCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thirdColorCheckBoxActionPerformed(evt);
            }
        });

        intensityLabel.setText("1st color intensity:");
        intensityLabel.setEnabled(false);

        intensitySlider.setMaximum(99);
        intensitySlider.setMinimum(1);
        intensitySlider.setPaintLabels(true);
        intensitySlider.setPaintTicks(true);
        intensitySlider.setSnapToTicks(true);
        intensitySlider.setEnabled(false);
        intensitySlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                intensitySliderStateChanged(evt);
            }
        });

        percentLabel.setText("50%");
        percentLabel.setEnabled(false);

        javax.swing.GroupLayout colorsPanelLayout = new javax.swing.GroupLayout(colorsPanel);
        colorsPanel.setLayout(colorsPanelLayout);
        colorsPanelLayout.setHorizontalGroup(
            colorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(colorsPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(colorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(colorsPanelLayout.createSequentialGroup()
                        .addComponent(intensitySlider, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(percentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(63, 63, 63))
                    .addGroup(colorsPanelLayout.createSequentialGroup()
                        .addComponent(intensityLabel)
                        .addContainerGap(209, Short.MAX_VALUE))))
            .addGroup(colorsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(colorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(color1Label)
                    .addComponent(color1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(colorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(color2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(color2Label))
                .addGap(32, 32, 32)
                .addGroup(colorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(colorsPanelLayout.createSequentialGroup()
                        .addComponent(color3Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(thirdColorCheckBox))
                    .addComponent(color3Label))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        colorsPanelLayout.setVerticalGroup(
            colorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, colorsPanelLayout.createSequentialGroup()
                .addGroup(colorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(colorsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(colorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(color1Label)
                            .addComponent(color2Label)
                            .addComponent(color3Label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(colorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(color3Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(color2Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(color1Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(41, 41, 41)
                        .addComponent(intensityLabel)
                        .addGap(0, 0, 0))
                    .addGroup(colorsPanelLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(thirdColorCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(colorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(percentLabel)
                    .addComponent(intensitySlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        helpMenu.setText("Help");
        helpMenuItem.setText("Content...");
        helpMenu.add(helpMenuItem);

        aboutMenuItem.setText("About...");
        helpMenu.add(aboutMenuItem);

        jMenuBar.add(helpMenu);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(typePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(parametersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mapPatternPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(colorsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(typePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(guidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(parametersPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(colorsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mapPatternPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void patternPreviewPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patternPreviewPanelMousePressed
	if ( this.patternPreviewPanel.isEnabled() ) {
	    int button = this.patternFileChooser.showOpenDialog( this );
	    if ( button == JFileChooser.APPROVE_OPTION ) {
		File f = this.patternFileChooser.getSelectedFile();
		if ( f != null && f.exists() && f.isFile() && f.canRead() ) {
		    BufferedImage bf = this.getImage( f );
		    if ( bf != null ) {
			this.patternPreviewPanel.setImage( bf );
		    }
		    else {
			this.patternPreviewPanel.resetImage();
			// TODO error
		    }
		}
		else {
		    this.patternPreviewPanel.resetImage();
		    // TODO error
		}
	    }
	}
    }//GEN-LAST:event_patternPreviewPanelMousePressed

    private void mapPreviewPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mapPreviewPanelMousePressed
	if ( this.mapPreviewPanel.isEnabled() ) {
	    int button = this.mapFileChooser.showOpenDialog( this );
	    if ( button == JFileChooser.APPROVE_OPTION ) {
		File f = this.mapFileChooser.getSelectedFile();
		if ( f != null && f.exists() && f.isFile() && f.canRead() ) {
		    BufferedImage bf = this.getImage( f );
		    if ( bf != null ) {
			this.mapPreviewPanel.setImage( bf );
		    }
		    else {
			this.mapPreviewPanel.resetImage();
			// TODO error
		    }
		}
		else {
		    this.mapPreviewPanel.resetImage();
		    // TODO error
		}
	    }
	}
    }//GEN-LAST:event_mapPreviewPanelMousePressed

    private void intensitySliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_intensitySliderStateChanged
	if ( this.intensitySlider.isEnabled() ) {
	    int value = this.intensitySlider.getValue();
	    this.percentLabel.setText( value + "%" );
	}
    }//GEN-LAST:event_intensitySliderStateChanged

    private void color3PanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_color3PanelMousePressed
	this.handleColorChooser( this.color3Panel, 3);
    }//GEN-LAST:event_color3PanelMousePressed

    private void color2PanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_color2PanelMousePressed
	this.handleColorChooser( this.color2Panel, 2);
    }//GEN-LAST:event_color2PanelMousePressed

    private void color1PanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_color1PanelMousePressed
	this.handleColorChooser( this.color1Panel, 1);
    }//GEN-LAST:event_color1PanelMousePressed

	private void handleColorChooser( JPanel colorPanel, int panelNumber) {
		if ( colorPanel.isEnabled() ) {
		    Color newColor = this.colorChooser.showDialog( this, "Select color " + panelNumber, colorPanel.getBackground() );
		    if ( newColor != null ) {
			colorPanel.setBackground( newColor );
		    }
		}
	}

    private void textRadioButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_textRadioButtonStateChanged
	if ( this.textRadioButton.isSelected() ) {
	    this.textLabel.setEnabled( true );
	    this.textTextField.setEnabled( true );
	    this.sizeLabel.setEnabled( true );
	    this.sizeSpinner.setEnabled( true );
	
	    this.mapLabel.setEnabled( false );
	    this.mapPreviewPanel.setEnabled( false );
	}
	else {
	    this.textLabel.setEnabled( false );
	    this.textTextField.setEnabled( false );
	    this.sizeLabel.setEnabled( false );
	    this.sizeSpinner.setEnabled( false );
	
	    this.mapLabel.setEnabled( true );
	    this.mapPreviewPanel.setEnabled( true );
	}
    }//GEN-LAST:event_textRadioButtonStateChanged

    private void dottedRadioButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_dottedRadioButtonStateChanged
	if ( this.dottedRadioButton.isSelected() ) {
	    this.patternLabel.setEnabled( false );
	    this.patternPreviewPanel.setEnabled( false );
	    
	    this.hPpiLabel.setEnabled( false );
	    this.hPpiTextField.setEnabled( false );
		    
	    this.color1Label.setEnabled( true );
	    this.color1Panel.setEnabled( true );
	    this.color2Label.setEnabled( true );
	    this.color2Panel.setEnabled( true );
	    this.thirdColorCheckBox.setEnabled( true );
	    this.thirdColorCheckBoxActionPerformed( null );
	}
	else {
	    this.patternLabel.setEnabled( true );
	    this.patternPreviewPanel.setEnabled( true );
	    
	    this.hPpiLabel.setEnabled( true );
	    this.hPpiTextField.setEnabled( true );
	    
	    this.color1Label.setEnabled( false );
	    this.color1Panel.setEnabled( false );
	    this.color2Label.setEnabled( false );
	    this.color2Panel.setEnabled( false );
	    this.color3Label.setEnabled( false );
	    this.color3Panel.setEnabled( false );
	    this.thirdColorCheckBox.setEnabled( false );
	    this.intensityLabel.setEnabled( false );
	    this.intensitySlider.setEnabled( false );
	    this.percentLabel.setEnabled( false );		    
	}
    }//GEN-LAST:event_dottedRadioButtonStateChanged

    private void thirdColorCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thirdColorCheckBoxActionPerformed
	if ( this.thirdColorCheckBox.isSelected() ) {
	    this.color3Label.setEnabled( true );
	    this.color3Panel.setEnabled( true );
	    this.intensityLabel.setEnabled( false );
	    this.intensitySlider.setEnabled( false ); 
	    this.percentLabel.setEnabled( false );
	}
	else {
	    this.color3Label.setEnabled( false );
	    this.color3Panel.setEnabled( false );
	    this.intensityLabel.setEnabled( true );
	    this.intensitySlider.setEnabled( true ); 
	    this.percentLabel.setEnabled( true );
	}
    }//GEN-LAST:event_thirdColorCheckBoxActionPerformed
        
    	private BufferedImage getImage(File file) {
		try {
			BufferedImage bf = ImageIO.read( file );
			return bf;
		}
		catch (Exception e) {
			return null;
		}
	}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new MainGUI().setVisible(true);
	    }
	});
    }
    
    // Declaração de variáveis - não modifique//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JLabel color1Label;
    private javax.swing.JPanel color1Panel;
    private javax.swing.JLabel color2Label;
    private javax.swing.JPanel color2Panel;
    private javax.swing.JLabel color3Label;
    private javax.swing.JPanel color3Panel;
    private javax.swing.JColorChooser colorChooser;
    private javax.swing.JPanel colorsPanel;
    private javax.swing.JRadioButton dottedRadioButton;
    private javax.swing.ButtonGroup elementButtonGroup;
    private javax.swing.JLabel elementLabel;
    private javax.swing.JLabel eyeLabel;
    private javax.swing.JTextField eyeTextField;
    private javax.swing.JButton generateButton;
    private javax.swing.JPanel guideImagePanel;
    private javax.swing.JPanel guidePanel;
    private javax.swing.JLabel hPpiLabel;
    private javax.swing.JTextField hPpiTextField;
    private javax.swing.JLabel heighLabel;
    private javax.swing.JTextField heighTextField;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem helpMenuItem;
    private javax.swing.JLabel intensityLabel;
    private javax.swing.JSlider intensitySlider;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.ButtonGroup lookButtonGroup;
    private javax.swing.JLabel lookLabel;
    private javax.swing.JFileChooser mapFileChooser;
    private javax.swing.JLabel mapLabel;
    private javax.swing.JPanel mapPatternPanel;
    private br.gfca.openstereogram.gui.ImagePreviewPanel mapPreviewPanel;
    private javax.swing.JRadioButton mapRadioButton;
    private javax.swing.JLabel maxDepthLabel;
    private javax.swing.JTextField maxDepthTextField;
    private javax.swing.JLabel minDepthLabel;
    private javax.swing.JTextField minDepthTextField;
    private javax.swing.JLabel observationLabel;
    private javax.swing.JTextField observationTextField;
    private javax.swing.JPanel parametersPanel;
    private javax.swing.JFileChooser patternFileChooser;
    private javax.swing.JLabel patternLabel;
    private br.gfca.openstereogram.gui.ImagePreviewPanel patternPreviewPanel;
    private javax.swing.JLabel percentLabel;
    private javax.swing.JLabel sizeLabel;
    private javax.swing.JSpinner sizeSpinner;
    private javax.swing.JLabel textLabel;
    private javax.swing.JRadioButton textRadioButton;
    private javax.swing.JTextField textTextField;
    private javax.swing.JRadioButton texturedRadioButton;
    private javax.swing.JCheckBox thirdColorCheckBox;
    private javax.swing.JPanel typePanel;
    private javax.swing.JLabel vPpiLabel;
    private javax.swing.JTextField vPpiTextField;
    private javax.swing.JLabel widthLabel;
    private javax.swing.JTextField widthTextField;
    // Fim da declaração de variáveis//GEN-END:variables
    
}
